<a href="https://colab.research.google.com/github/BinaryBrainsUPIICSA/Apuntes_Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introducción

In [ ]:
import numpy as np

Crear un arreglo en NumPy


Un arreglo es: Estructura de datos que nos pertmite almacenar datos, estos datos deben ser del mismo tipo.

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Conocer la cantidad de elementos del array

In [ ]:
print(a.size)

5


Conocer la cantidad de dimensiones que contiene un arreglo

In [ ]:
print(a.ndim)

1


Conocer qué tipo de datos contiene el arreglo

In [ ]:
print(a.dtype)

int64


Conocer las dimensiones y elementos dentro del arreglo

In [ ]:
print(a.shape)

(5,)


**UNA VEZ QUE SE HA DEFINIDO LA LONGITUD DEL ARREGLO YA NO SE PODRÁ MODIFICAR**

## OPERACIONES

Si queremos hacer el cálculo de todo un array, sin NumPy , no se podrá realizar, sin embargo si lo utilizamos una de las bondades con las que cuenta esta librería es que nos permite poder realizar este tipo de operaciones.

In [ ]:
numeros = np.array([5,10,15,20,25])

In [ ]:
print(numeros)

[ 5 10 15 20 25]


si quiero añadir 10 a c/u de los elementos del arreglo

In [ ]:
numeros + 10

array([15, 20, 25, 30, 35])

Podemos observar que el arreglo orginal no fue modificado

In [ ]:
print(numeros)

[ 5 10 15 20 25]


In [ ]:
arreglo_a = np.array([6,12,18,24,30])
arreglo_b = np.array([5,10,15,20,25])

In [ ]:
print(arreglo_a + arreglo_b)

[11 22 33 44 55]


In [ ]:
resultado = arreglo_a / arreglo_b ** 2
print(resultado)

[0.24  0.12  0.08  0.06  0.048]


Ejemplo de lo que sucedería si no usaramos NumPy

In [ ]:
weigth= [65.4,59.2,63.6,88.4,68.7]
height=[1.73,1.68,1.71,1.89,1.79]
weigth / height ** 2

TypeError: ignored

## TIPOS DE DATOS

Definir exactamente tipo de dato qué tipo de dato vamos a poner dentro del arreglo.

Si queremos cambiar el tipo de dato que será un arreglo, se había visto anteriormente que se podía hacer de la siguiente forma.

In [ ]:
x = np.array(str([1,2,3,4,5]))

In [ ]:
x

array('[1, 2, 3, 4, 5]', dtype='<U15')

Como podemos ver al hacerlo de esta forma no estamos transformando a c/u de los datos en STR, por lo que la manera correcta hacerlo será la siguiente:

In [ ]:
y = np.array([1,2,3,4,5], dtype= str)

In [ ]:
print(y)

['1' '2' '3' '4' '5']


In [ ]:
y = np.array([1,2,3,4,5], dtype= bool)

In [ ]:
print(y)

[ True  True  True  True  True]


In [ ]:
y = np.array([1,2,3,4,5], dtype= float)

In [ ]:
print(y)

[1. 2. 3. 4. 5.]


## Crear arreglos

crear un arreglo a partir de un rango.

In [ ]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Crear arreglos de ceros.

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

crear arreglo con numeros enteros aleatorios

In [ ]:
# (inicio, final, numelementos)
np.random.randint(0, 100, 50)

array([ 9, 80,  6, 30, 34, 45, 90, 70, 13, 80,  7, 84, 52, 17, 50, 73, 23,
       67, 22, 38, 13, 76, 89, 44, 28, 39, 68,  8, 57, 83, 12,  0, 14, 84,
       98, 28, 52, 89, 60, 90, 69, 52, 69, 27, 21, 90, 82, 42, 52, 67])

crear arreglo con numeros float aleatorios

In [ ]:
rango_linspace = np.linspace(1.0, 6.0, 10)
print(rango_linspace)

[1.         1.55555556 2.11111111 2.66666667 3.22222222 3.77777778
 4.33333333 4.88888889 5.44444444 6.        ]


## Obtener y actualizar datos del arreglo

In [ ]:
a = np.random.randint(0,10,10)
print(a)

[3 5 3 6 5 0 2 1 4 9]


Obtener datos

In [ ]:
print(a[0])

3


In [ ]:
print(a[-2])

4


Cambiar datos

In [ ]:
a[0]= 100
print(a)

[100   5   3   6   5   0   2   1   4   9]


## SubArreglos

In [ ]:
num_randoms = np.random.randint(0, 50, 80)
print(num_randoms)

[23 48  0  1  9 44 49 38 43 40  6 41 22 47 20 41 20 23 34  9  5 11  6 48
 10 29 24 24 40 25 31 23 14 10 22 49 15 30 25 41 13 30 30 28  2 17 10 21
 15 11 45 48 44 13  8 38 37 30 10 28 28  8 40 43 44 33 29 39 26  7 24 27
 20 27 47 29  0 16 16 43]


In [ ]:
# [inicio:finial:saltos]
print(num_randoms[:20])

[23 48  0  1  9 44 49 38 43 40  6 41 22 47 20 41 20 23 34  9]


¿Cómo podríamos consultar datos específicos dentro del arreglo?

In [ ]:
print(num_randoms[[1,4,20]])

[48  9  5]


## Vectorizar funciones

In [ ]:
z = np.random.randint(0,10,20)
print(z)

[1 3 4 9 0 8 9 6 1 9 3 8 0 5 3 0 2 5 2 8]


In [ ]:
def operacion(valor):
    return (valor ** 2) + 2
    """
    Args: valor

    return (3 ** 2) + 2
    """
operacion(3)

11

In [ ]:
operacion(z)

array([ 3, 11, 18, 83,  2, 66, 83, 38,  3, 83, 11, 66,  2, 27, 11,  2,  6,
       27,  6, 66])

In [ ]:
for valor in z:
    print(operacion(valor))

3
11
18
83
2
66
83
38
3
83
11
66
2
27
11
2
6
27
6
66


con vectorize

In [ ]:
vector = np.vectorize(operacion)
vector(z)

array([ 3, 11, 18, 83,  2, 66, 83, 38,  3, 83, 11, 66,  2, 27, 11,  2,  6,
       27,  6, 66])